name: æ›´æ–°EPGèŠ‚ç›®å•

on:
  workflow_dispatch:  # æ‰‹åŠ¨è§¦å‘
#  schedule:
#  # åŒ—äº¬æ—¶é—´å‡Œæ™¨2ç‚¹ = UTCæ—¶é—´å‰ä¸€å¤©18ç‚¹
#  - cron: '15 16,18,20,22,0,2,4,6,8,10,12,14 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: ä¸‹è½½åŸå§‹IPTVæ–‡ä»¶
      run: |
        wget -q https://epg.112114.xyz/pp.xml -O 112114_1d_epg.xml

    - name: æ¨é€åˆ°Gitee
      run: |
        # æ£€æŸ¥tokenæ˜¯å¦å­˜åœ¨
        if [ -z "${{ secrets.GITEE_TOKEN }}" ]; then
          echo "âŒ GITEE_TOKEN æœªè®¾ç½®"
          echo "è¯·åœ¨ä»“åº“ Settings â†’ Secrets and variables â†’ Actions ä¸­è®¾ç½® GITEE_TOKEN"
          exit 1
        fi
        # è®¾ç½®å˜é‡
        USER="tyrian9905"    # â† ç”¨æˆ·å
        REPO="iptv"        # â† ä»“åº“å

        
        # é…ç½®Git
        git config --global user.name "Auto Sync"
        git config --global user.email "auto@sync.com"
        
        export TZ='Asia/Shanghai'
        # è·å–åŒ—äº¬æ—¶é—´
        BEIJING_TIME=$(date '+%Y-%m-%d %H:%M:%S')
        
        # å…‹éš†ä»“åº“
        git clone https://oauth2:${{ secrets.GITEE_TOKEN }}@gitee.com/tyrian9905/iptv.git
        
        # è¿›å…¥ä»“åº“å¹¶æ›´æ–°æ–‡ä»¶
        cd ${REPO}
        
        # å¤åˆ¶æ–‡ä»¶
        cp ../112114_1d_epg.xml ./
        
        # æäº¤å¹¶æ¨é€
        git add 112114_1d_epg.xml
        git commit -m "è‡ªåŠ¨åŒæ­¥ ${BEIJING_TIME}"
        git push origin master
        
        echo "ğŸ‰ èŠ‚ç›®å•EPGæˆåŠŸï¼"
