name:  清理运行记录

on:
  schedule:
    # 每周一北京时间 5 点清理一次（根据需要调整频率）
    - cron: '0 13 * * 1'
  workflow_dispatch:  # 可选：允许手动触发

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const runs = await github.paginate(
              github.rest.actions.listWorkflowRunsForRepo,
              { owner: context.repo.owner, repo: context.repo.repo }
            );
            await Promise.all(runs.slice(50).map(run => 
              github.rest.actions.deleteWorkflowRun({
                owner: context.repo.owner, repo: context.repo.repo, run_id: run.id
              })
            ));
